---
# Padrões de hardware para as novas VMs
default_vm_cores: 2
default_vm_memory: 2048  # Em MB

# Padrões de usuário e senha para as novas VMs (Linux)
# IMPORTANTE: Seu template precisa ter o cloud-init instalado e configurado
# para que estas configurações sejam aplicadas na criação.
default_vm_user: "ubuntu"
default_vm_password: "ijo1Epaing5"

# Padrões para cálculo de VM ID
vmid_range_start: 700